# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - EMSProject6

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_ebf754329ddd447b90eaa5d3e0217c36 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_abe614182b09431a911e4cf4c4031dcc }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_ebf754329ddd447b90eaa5d3e0217c36 }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'EMSProject6'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_d84675f97b3d4e73892658bc8d0c07ed }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_ebf754329ddd447b90eaa5d3e0217c36 }}/appsvc/staticsite:${{ github.sha }}'